### ISSUE TITLE
how to use asio mode

### ISSUE THREAD

**Issue by soncfe** [BlueDragon28/simple-audio-library#1] opened 2023-03-15 00:49 UTC
PortAudioRAII init and AudioPlayer::loop thread can't work together on steam ASIO MODE.

**Comment by BlueDragon28** [comment] 2023-03-15 13:06
Bug confirmed, I will look into it. Thanks for opening the issue.

**Comment by BlueDragon28** [comment] 2023-03-15 18:12
I moved the initialization of PortAudio into the same thread as the main loop. Now ASIO is working. Howether, for some reason when starting a new playback, the app crash.

**Comment by soncfe** [comment] 2023-03-15 23:21
> I moved the initialization of PortAudio into the same thread as the main loop. Now ASIO is working. Howether, for some reason when starting a new playback, the app crash.

the 192khz/24bit flac worked poor，It's a problem about the sream buffer setting.

**Comment by BlueDragon28** [comment] 2023-03-16 15:18
Crash of ASIO when buffering fixed by disabling the default behaviour of pausing the stream until enough data has been read from the audio file 39221bcfb8c79335e45b1e07556ca4f146363309.

**Comment by BlueDragon28** [comment] 2023-03-16 15:24
Set stream frames per buffer size to paFramesPerBufferUnspecified. The buffer size will now be set by the system based on what is needed 82bea22acee861e4c231bc91512258f5cea59e75. Can you confirm that the problem is gone?

**Comment by soncfe** [comment] 2023-03-17 01:31
> Set stream frames per buffer size to paFramesPerBufferUnspecified. The buffer size will now be set by the system based on what is needed [82bea22](https://github.com/BlueDragon28/simple-audio-library/commit/82bea22acee861e4c231bc91512258f5cea59e75). Can you confirm that the problem is gone?
the FLAC 192KHZ/24bit worked on ASIO, there is still some noise when steam is playing.
But 192khz/24bit on the Pa_GetDefaultOutputDevice() (mme mode) or flac 48khz/24bit on ASIO can woker better, 
I think the FlacAudioFile's that not support the HiRes audio.

**Comment by BlueDragon28** [comment] 2023-03-17 09:55
> the FLAC 192KHZ/24bit worked on ASIO, there is still some noise when steam is playing.

Good to hear. 

I think the problem is more of a race condition, but I can't be sure because I do not have any problem on my side. I think, one possible solution will be to compile SAL in release mode using the cmake option `-DCMAKE_BUILD_TYPE=Release`. I this case, the code will be optimized by the compiler and will run faster. That could possibly fix the problem.  Another temporary solution will be to disable the integrated FLAC support of SAL and let libsndfile library (disabled by default) decode it.

The best way to fix the problem will be to add multi-threading support while reading the file. It could help or make the situation worse. But this is a complex approach and will take some time to implement.

> But 192khz/24bit on the Pa_GetDefaultOutputDevice() (mme mode)

SAL let portaudio select the most appropriate backend wich is MME on Windows. If it doesn't it probably because you disabled the MME support while compiling PortAudio.

> or flac 48khz/24bit on ASIO can woker better

I do not think the problem come from ASIO and adding another layer of resampling will only make the situation worse.

Anyway, this is not an ASIO related problem, so I opened another issue #2.

Thank you for the time you put in testing the SAL.

**Closed as completed by BlueDragon28** 2023-03-17 09:55 UTC
Labels: bug
